---
title: "Reproducibility report for Arns 2015 by EGG analytic pipeline to predict treatment outcome in patients with depression (2022, Neuropsychopharmacology)"
author: "Oscar D. Mier (omier@Stanford.edu)"
date: "10/09/2022"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Reproducibility reports should all use this template to standardize reporting across projects. These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

Reproduction of Arns et al (2015)'s, "Frontal and rostral anterior cingulate (rACC) EEG in depression: Implications for treatment outcome?" My research interests consist of clinical and translational neuroscience-informed precision psychiatry research. More specifically, resting state electroencephalogram brain biomarkers to predict treatment outcomes in patients with Major Depressive Disorder (MDD). I chose this paper because it allows me to directly explore that field, develop my EEG data analytical skills, and I am interested in Dr. Leanne Williams's precision psychiatry research at Stanford University School of Medicine. There are large neuroimaging and neurophysiological databases available; therefore, focusing on learning how to analyze that mass data will be the most beneficial since I have extensive experience obtaining neuroimaging and clinical data.

The EEG data exists within the international Study to Predict Optimized Treatment in Depression (iSPOT-D) database. I have obtained access to that data by reaching out to one of the data managers of that study and requesting non PHI data access. The stimuli in that sample were Sertaline and extended-release Venlafaxine treatments in an eight-week period with baseline resting state EEG sessions. Sertaline is a selective serotonin reuptake inhibitor (SSRI). Venlafaxine XR is a serotonin-norepinephrine reuptake inhibitor (SNRI) 

There are two key analyses in the original paper: first, to determine if resting state eyes closed electroencephalogram (rsEEG) low theta waves within the rostral anterior cortex and frontal cortex correlate with Sertraline and Venlafaxine XR treatment response and remission in the sample; secondly, to determine if rsEEG low theta waves in the right frontal and medial-frontal area predict treatment outcome with extended-release Venlafaxine. Treatment response was determined through the Hamilton Rating Scale for Depression 17 (HRSD17). The anticipated challenges will be correcting for multiple comparisons, preprocessing the EEG data, rACC source localization with EEG data, and replicating the data analyzing pipeline with newer versions of the eLORETA software utilized in the data analysis phase of the study.   

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

Current phasic theta wave desnity in the rostral anterior cingulate (rACC) estimated by eLORETA.

### Justification for choice of study

Please describe why you chose to reproduce the results of this study.

* Written above in introduction

### Anticipated challenges

Do you anticipate running into any challenges when attempting to reproduce these result(s)? If so please, list them here.

* Written above in introduction

### Links
eLORETA EEG localization information website: http://www.uzh.ch/keyinst/loreta.htm. 
Project repository (on Github): https://github.com/psych251/arns2015

Original paper (as hosted in your repo): https://github.com/psych251/arns2015/tree/main/original_paper

Python: https://www.python.org/downloads/
MNE Library: https://mne.tools/stable/index.html
MNE eLORETA library: https://mne.tools/stable/auto_tutorials/inverse/30_mne_dspm_loreta.html
NumPy: https://numpy.org/

## Methods

The original paper used EEG eLORETA software for source localization and for investigating treatment prediction, a repeated measure ANOVA was conducted with within-subject factors site (Frontal and rACC). When significant interactions were found, univariate analyses were performed. .The participants conducted resting state eyes closed EEG sessions for two minutes at baseline visit and at the week-eight timepoint.The participants depression states, response to treatment, and remission state were determined from HRSD17. A score of greater than or equal to 16 meant the participants were depressed. Remission was defined as a score of less than or equal to 7 on the HRSD17 scale at the 8-week time point. Treatment response was less than 50% on the HRSD17 scale from the baseline visit. Furthermore, the original data is from iSPOT-D which a multi-center (20 sites), international, randomized, prospective practical trial. The original study had a ecological validity perspective which influenced them to not have a placebo control group to mimic real-world practice. At baseline visit the study used a mini-international neuropsychiatric interview (MINI-Plus) to diagnose the participants with nonpsychotic MDD. After baseline visit, participants were randomized into different treatment groups. The treatment period lasted 8-weeks. Participants underwent EEG sessions at baseline and at the end of treatment. EEG data was acquired from 26 channels: Fp1, Fp2, F7, F3, Fz, F4, F8, FC3, FCz, FC4, T3, C3, Cz, C4, T4m CP3, CPz, CP4, T5, P3, Pz, P4, T6, 01, Oz, and O2. 

### Description of the steps required to reproduce the results

Please describe all the steps necessary to reproduce the key result(s) of this study.
(1) Obtain resting state eyes closed EEG data and HSRD17 scores.
(2) Seperate data into four groups:
  - SSRI treatment response group
  - SSRI treatment non-response group
  - SNRI treatment response group
  - SNRI treatment non-response group
(3) Create analyzing pipeline
  - quality control: remove artifacts
  - sampling rate of all channels was 500 Hz.
  - Low pass filter = 100 Hz
  - High pass filter = 0.3 Hz
  - Notch filters of 50 or 60 Hz.
  - Electrooculgram (EOG)-corrected using a regression-based technique.  
  - segment data into 4s epochs (50% overlapping).
  - artefact removal: EMG detection, pulse and baseline shift detection, crosstalk detection,     high kurtosis, extreme power level detection, residual eye blink detection, and extreme       voltage swing detection. 
  - Use a spherical spine interpolation to replace rejected channels. 
  - With eLORETA software, extract 6.5-8Hz theta waves from the rACC and frontal voxels. 
  - brain masking (making the brains the same sizes)
  - localize regions of interests in EEG data (tissue classification and segmentation)
  - Power Spectral Analysis*
  - log transform theta measures before statistical analysis. 
(4) Push data through pipeline 


### Differences from original study

Versions of software and writing the analyzing pipeline code in the same method as the original paper will be challenging. This reprodcibility study is using the following Python libraries: MNE version 1.2.1 for EEG analysis and visualization, and NumPy version 1.23.0. This replica study is using a MacBook Pro (2021) with an Apple M1 Pro chip, 16 GB Memory, and with macOS Ventura 13.0 version. The macOS contains Python version 3.9.13 running on PyCharm 2022.2.2 (community Edition). VM for PyCharm is OpenJDK 64-Bit Server VM by JetBrains s.r.o. 

Explicitly describe known differences in the analysis pipeline between the original paper and yours (e.g., computing environment). The goal, of course, is to minimize those differences, but differences may occur. Also, note whether such differences are anticipated to influence your ability to reproduce the original results. 

### Results in original paper

The result of interest in the original paper is the phasic theta wave density relationship to treatment response. significant correlations were found between HRSD17 scores and rACC theta waves at the 8-week timepoint. P = 0.21; r = 0.093, and DF = 608. 

## Project Progress Check 1

### Measure of success

Please describe the outcome measure for the success or failure of your reproduction and how this outcome will be computed.


### Pipeline progress

Earlier in this report, you described the steps necessary to reproduce the key result(s) of this study. Please describe your progress on each of these steps (e.g., data preprocessing, model fitting, model evaluation).

- Obtained ~ 400 rsEEG data and HSRD17 scores from iSPOTD.
- Stored EEG data in cloud storage (Amazon AWS).
- Installed MNE library onto python
- Installed NumPy library onto python 


### Data preparation

Data preparation following the analysis plan.

- ANOVA and linear regression 

	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

# Data stored on Amazon AWS as read only 

#### Data exclusion / filtering: source Localization with eLORETA 

# -*- coding: utf-8 -*-
"""
.. _tut-inverse-methods:

========================================================
Source localization with MNE, dSPM, sLORETA, and eLORETA
========================================================

The aim of this tutorial is to teach you how to compute and apply a linear
minimum-norm inverse method on evoked/raw/epochs data.
"""

# %%

import numpy as np
import matplotlib.pyplot as plt

import mne
from mne.datasets import sample
from mne.minimum_norm import make_inverse_operator, apply_inverse

# %%
# Process MEG data

data_path = sample.data_path()
raw_fname = data_path / 'MEG' / 'sample' / 'sample_audvis_filt-0-40_raw.fif'

raw = mne.io.read_raw_fif(raw_fname)  # already has an average reference
events = mne.find_events(raw, stim_channel='STI 014')

event_id = dict(aud_l=1)  # event trigger and conditions
tmin = -0.2  # start of each epoch (200ms before the trigger)
tmax = 0.5  # end of each epoch (500ms after the trigger)
raw.info['bads'] = ['MEG 2443', 'EEG 053']
baseline = (None, 0)  # means from the first instant to t = 0
reject = dict(grad=4000e-13, mag=4e-12, eog=150e-6)

epochs = mne.Epochs(raw, events, event_id, tmin, tmax, proj=True,
                    picks=('meg', 'eog'), baseline=baseline, reject=reject)

# %%
# Compute regularized noise covariance
# ------------------------------------
# For more details see :ref:`tut-compute-covariance`.

noise_cov = mne.compute_covariance(
    epochs, tmax=0., method=['shrunk', 'empirical'], rank=None, verbose=True)

fig_cov, fig_spectra = mne.viz.plot_cov(noise_cov, raw.info)

# %%
# Compute the evoked response
# ---------------------------
# Let's just use the MEG channels for simplicity.

evoked = epochs.average().pick('meg')
evoked.plot(time_unit='s')
evoked.plot_topomap(times=np.linspace(0.05, 0.15, 5), ch_type='mag')

# %%
# It's also a good idea to look at whitened data:

evoked.plot_white(noise_cov, time_unit='s')
del epochs, raw  # to save memory

# %%
# Inverse modeling: MNE/dSPM on evoked and raw data
# -------------------------------------------------
# Here we first read the forward solution. You will likely need to compute
# one for your own data -- see :ref:`tut-forward` for information on how
# to do it.

fname_fwd = data_path / 'MEG' / 'sample' / 'sample_audvis-meg-oct-6-fwd.fif'
fwd = mne.read_forward_solution(fname_fwd)

# %%
# Next, we make an MEG inverse operator.

inverse_operator = make_inverse_operator(
    evoked.info, fwd, noise_cov, loose=0.2, depth=0.8)
del fwd

# You can write it to disk with::
#
#     >>> from mne.minimum_norm import write_inverse_operator
#     >>> write_inverse_operator('sample_audvis-meg-oct-6-inv.fif',
#                                inverse_operator)

# %%
# Compute inverse solution
# ------------------------
# We can use this to compute the inverse solution and obtain source time
# courses:

method = "dSPM"
snr = 3.
lambda2 = 1. / snr ** 2
stc, residual = apply_inverse(evoked, inverse_operator, lambda2,
                              method=method, pick_ori=None,
                              return_residual=True, verbose=True)

# %%
# Visualization
# -------------
# We can look at different dipole activations:

fig, ax = plt.subplots()
ax.plot(1e3 * stc.times, stc.data[::100, :].T)
ax.set(xlabel='time (ms)', ylabel='%s value' % method)

# %%
# Examine the original data and the residual after fitting:

fig, axes = plt.subplots(2, 1)
evoked.plot(axes=axes)
for ax in axes:
    for text in list(ax.texts):
        text.remove()
    for line in ax.lines:
        line.set_color('#98df81')
residual.plot(axes=axes)

# %%
# Here we use peak getter to move visualization to the time point of the peak
# and draw a marker at the maximum peak vertex.

# sphinx_gallery_thumbnail_number = 9

vertno_max, time_max = stc.get_peak(hemi='rh')

subjects_dir = data_path / 'subjects'
surfer_kwargs = dict(
    hemi='rh', subjects_dir=subjects_dir,
    clim=dict(kind='value', lims=[8, 12, 15]), views='lateral',
    initial_time=time_max, time_unit='s', size=(800, 800), smoothing_steps=10)
brain = stc.plot(**surfer_kwargs)
brain.add_foci(vertno_max, coords_as_verts=True, hemi='rh', color='blue',
               scale_factor=0.6, alpha=0.5)
brain.add_text(0.1, 0.9, 'dSPM (plus location of maximal activation)', 'title',
               font_size=14)

# The documentation website's movie is generated with:
# brain.save_movie(..., tmin=0.05, tmax=0.15, interpolation='linear',
#                  time_dilation=20, framerate=10, time_viewer=True)

# %%
# There are many other ways to visualize and work with source data, see
# for example:
#
# - :ref:`tut-viz-stcs`
# - :ref:`ex-morph-surface`
# - :ref:`ex-morph-volume`
# - :ref:`ex-vector-mne-solution`
# - :ref:`tut-dipole-orientations`
# - :ref:`tut-mne-fixed-free`
# - :ref:`examples using apply_inverse
#   <sphx_glr_backreferences_mne.minimum_norm.apply_inverse>`.

#### Prepare data for analysis - create columns etc.
```

### Key analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.
